title: Just starting out
author: Pedro Sandoval
email: ssandoval0519@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
At 41 I begin my coding jpurney. lots to take in.

# social links
github_username: Tavyus2

show_excerpts: false # set to false to remove excerpts on the homepage
